### ISSUE TITLE
Request Support Runtime load camera

### ISSUE THREAD

**Issue by fingerx** [rdeioris/glTFRuntime-docs#1]
thanks for work,can your add  support runtime load camera from gltf?thanks

**Comment by rdeioris** [comment]
Hi @fingerx camera support has been added in master branch.

There are currently 4 functions exposed:

```cpp
TArray<FString> GetCamerasNames();
ACameraActor* LoadNodeCamera(UObject* WorldContextObject, const int32 NodeIndex, TSubclassOf<ACameraActor> CameraActorClass);
TArray<int32> GetCameraNodesIndices();
bool LoadCamera(const int32 CameraIndex, UCameraComponent* CameraComponent);
```

If You use the included AssetActor it will load the cameras automatically (included animations, just assign the current view target to one of them, if you are in editor just 'eject' and click over the camera component you want to inspect)

**Comment by fingerx** [comment]
@rdeioris  thanks
