### ISSUE TITLE
Complex Collisions Don't Work

### ISSUE THREAD

**Issue by IstyManame** [rdeioris/glTFRuntime-docs#15]
On loading Static Mesh from gltf asset i check the "allowCPUaccess", "Build Complex Collision", and "Use Complex Collision As Simple" options. My Line Traces go straight through. If i also check the "Build Simple Collision" it starts to use this simple inaccurate collision even though "Use Complex Collision As Simple" is still enabled. Screenshots Attached. Thanks in advance
![image](https://github.com/rdeioris/glTFRuntime-docs/assets/108396604/a33fca96-f8ad-400d-af7c-c9ef1270424b)
![image](https://github.com/rdeioris/glTFRuntime-docs/assets/108396604/8bebdecb-f695-4c76-baf9-909d0c6f5677)

**Comment by rdeioris** [comment]
Hi, you need to set the Outer too (check https://github.com/rdeioris/glTFRuntime/blob/master/Source/glTFRuntime/Private/glTFRuntimeAssetActor.cpp#L175 for an example setting the staticmeshcomponent as the outer).

Note that if you need mobile support you need unreal 5.4 (previous versions do not support runtime complex collisions on android and ios)

**Comment by IstyManame** [comment]
Got it thanks, but is that c++ thing only? My knowledge of c++ is pretty basic and I'm not sure what part of this example to take and where to put it. In my project i use my actor with static mesh component and then load and set static mesh in it

**Comment by IstyManame** [comment]
> Hi, you need to set the Outer too (check https://github.com/rdeioris/glTFRuntime/blob/master/Source/glTFRuntime/Private/glTFRuntimeAssetActor.cpp#L175 for an example setting the staticmeshcomponent as the outer).
> 
> Note that if you need mobile support you need unreal 5.4 (previous versions do not support runtime complex collisions on android and ios)

Should i create a new c++ actor, set the outer there, and set it as parent to my blueprint actor? There's no logic written inside this blueprint it's just a holder for static mesh coomponents

**Comment by rdeioris** [comment]
There is no need for using C++, you just need to assign the Outer field in the StaticMeshConfig structure in the blueprint node

**Comment by IstyManame** [comment]
Ahh ok thank you so much for your patience it works now!
