### ISSUE TITLE
How can i Convert *bin and Textures to Only One *.gltf  to use?

### ISSUE THREAD

**Issue by wushujian** [rdeioris/glTFRuntime-docs#2]
I buyed this plugins ,but i dont know how to use in my work. I DownLoad some gltf from Sketch.com or Export from UE4, then 
 Called glTFLoadAssetfromFileName failed. here is the  Error: LoadPrimitive(): Unable to load POSITION attribute.

**Comment by rdeioris** [comment]
Hi, you should use gltf embedded files if you want the single-asset approach.

Otherwise just use the github version that includes support for loading external files.

Fell free to join the discord channel for help.
