### ISSUE TITLE
About merge

### ISSUE THREAD

**Issue by rtjia** [rdeioris/glTFRuntime-docs#21]
Question:
How to merege these skeleton/skeletalMesh at runtime? use SkeletalMeshConfig.bMergeAllBonesToBoneTree ?

Thanks a lot.

**Comment by rdeioris** [comment]
You need to use the function marked with "recursive" like LoadSkinnedMeshRecursiveAsRuntimeLOD. You can see an example here: https://github.com/rdeioris/glTFRuntime-docs/blob/master/Tutorials/RetargetingRPMAndMixamo.md#step-0-loading-the-rpm-avatar

**Comment by rtjia** [comment]
Sorry, I didn't express it clearly.
I have about 300 models ( 300 glTF files), each model consists of 20 bones. I can attach these 300 models (FSkeletalMeshComponet(s)) to one Actor, but the runtime performance is not good, so I want to merge these 300 independent models.
In fact, I use LoadSkinnedMeshRecursiveAsRuntimeLOD to get these 300 models, each model has 20 bones

**Comment by rdeioris** [comment]
So, they are from 300 different files ?

**Comment by rtjia** [comment]
I have tried to merge these skeletalmesh by USkeletalMergingLibrary::MergeMeshes , but there are always some errors, about the number of root nodes being greater than 1 and messed up materials.

Later, I thought this plugin should make it easier to merge multiple SkeletalMeshes.

**Comment by rdeioris** [comment]
You can try using this: https://github.com/rdeioris/glTFRuntime/blob/master/Source/glTFRuntime/Public/glTFRuntimeFunctionLibrary.h#L67

It takes an array of runtimelods and merges them in a single runtimelod (it should works if the skeletons are compatibles)

**Comment by rtjia** [comment]
I tested merging models with two models (.gltf), and it seems to be OK.(two models meshes seems ok. )I load two model in one actor, and use first "parser" object call LoadSkeletalMeshFromRuntimeLODs, .

But there is a small problem. The bones of the second model are not visible, but the meshes are displayed correctly. Is this method causing the skeleton (bones) to be lost?

	FglTFRuntimeMeshLOD newLOD = UglTFRuntimeFunctionLibrary::glTFMergeRuntimeLODs(_AllMeshLODs);
	TArray<FglTFRuntimeMeshLOD> LODs;
	LODs.Add(newLOD);
	USkeletalMesh*_CompositeMesh = **parser-**>LoadSkeletalMeshFromRuntimeLODs(LODs, -1, MergedSkeletalMeshConfig);

I wonder if this error is caused by the parser coming from the first model, so when I use this **parser** to execute LoadSkeletalMeshFromRuntimeLODs, the bones of the second model are lost (although both models are displayed), so should I refer to LoadSkeletalMeshFromRuntimeLODs and write a static function? It does not depend on the parser.

Thank you.

**Comment by rdeioris** [comment]
Did you end up with a skeletalmesh without a skeleton, or the names of the bones are just messed up ?

**Comment by rtjia** [comment]
Yes, after merged ,bone count is one, 
I get boneNum by this function:

int boneNum = _CompositeMesh->GetRefSkeleton().GetRawRefBoneInfo().Num();
UE_LOG(LogTemp, Warning, TEXT(" Merged Skeleton Bone Num : %d"), boneNum);

//output boneNum =1;
Yes, I get a SkeletalMesh without one bone, in fact ,the first skeleton with about 20 bones ,the second with 15 bones, mesh already merge , looks very good, but bones seems like lost.

Thanks a lot.

**Comment by rdeioris** [comment]
Can you provide a couple of those models so i can make a test? Thanks

**Comment by rtjia** [comment]
[gltf.zip](https://github.com/user-attachments/files/17101424/gltf.zip)

**Comment by rdeioris** [comment]
@rtjia the zip contains static meshes (no skeletons), is it normal?

**Comment by rtjia** [comment]
yes , it is normal, Because I only need rigid animation by program ;  i dont need animation curve ;  in my project the plugin works well, and every model ( gltf ) loaded and composite was success, all rigid animation is OK, very perfact . 
Only one quesetion, I have a lot of models (more than 300), so , i get more than 300 SkeletalMeshComponent on a AActor.... the fps....So , I test merge all and keep bone by Other function ,but exist some error...So far, the method in this plug-in is still used, and the effect is the best

Thank you.

**Comment by rdeioris** [comment]
Sorry, i fear two different topics are messing up. I am referring to your 300 skeletal models issue, so i need a couple of them for testing (and fixing) the merge. The zip you sent me contains static meshes not skeletals.

**Comment by rtjia** [comment]
Sorry, I didn't explain the problem clearly:
1. All the gltf files I processed do not contain skeleton information, only staticmesh, and all skeletons are generated by this plugin at runtime,

2. I want to Merge multiple SkeletalMeshes to one SkeletalMesh  ;  In this step, the bone information loses the bone information generated in the previous step.

3. BTW, all steps are completed at runtime.
[2gltf.zip](https://github.com/user-attachments/files/17121248/2gltf.zip)

**Comment by rdeioris** [comment]
Hi, I have added in master branch a new function glTFMergeRuntimeLODsWithSkeleton that takes into account the special configuration of non-skinned meshes recursively joined. Let me know if it works for you.

**Comment by rtjia** [comment]
OK, I'll test it and let you know the result.
Thanks again

**Comment by rtjia** [comment]
Test Result:
The merged mesh is displayed correctly, but the position is incorrect. I checked the glTFMergeRuntimeLODsWithSkeleton code and it seems that RuntimeLOD.AdditionalTransforms is not effective in SkeletalMesh.

My pseudocode workflow is as follows:
 //step1:Load one glTF
 for(TArray<FglTFRuntimeMeshLODs> : One glTF)
 { 
        //Collect FglTFRuntimeMeshLODs for every kelMesh of glTF result
       TArray<FglTFRuntimeMeshLODs>.Add(LODs) 
} 

//step2: Add delta transform for every FglTFRuntimeMeshLODs of glTF(Mesh) 
for(LOD : Array<FglTFRuntimeMeshLODs>) 
{
    FTransform delta;//(from my config file) 
    LOD.AdditionalTransforms.Add(rootDeltaTransform); 
} 

//step3: collect all FglTFRuntimeMeshLODs for all LODs of glTFs 
for(all FglTFRuntimeMeshLODs of glTF)
{
      Collect(Array<FglTFRuntimeMeshLODs>) 
} 

//step4: merge all FglTFRuntimeMeshLODs
glTFMergeRuntimeLODsWithSkeleton(LODs) 

//step5: 
 USkeletalMesh* CompositeMesh = LoadSkeletalMeshFromRuntimeLODs

**Comment by rdeioris** [comment]
When you say the position is incorrect, you mean the position of the bone associated to each part of the mesh ? So basically AdditionalTransform should be the bone position of the skeleton?

**Comment by rtjia** [comment]
yes, in my test case, I want to merge 5 skeletalMesh(5 gltf‘s), and ,every gltf file (LODs) has a delta Transform, I need set them to Correct position，and... merge the to a New Root at last .
But now ,  Setting the position of these five objects is invalid.

**Comment by rdeioris** [comment]
Hi, i have added support for AdditionalTransforms: not each bone gets the related AdditionalTransforms as the local position

**Comment by rtjia** [comment]
@rdeioris thanks ,This is exactly what I need
