### ISSUE TITLE
About LoadSkeletalMeshRecursiveAsync

### ISSUE THREAD

**Issue by rtjia** [rdeioris/glTFRuntime-docs#23]
I'm back again :-)

I need use Async at loadSkeletalMesh,  but i noticed function LoadSkeletalMeshRecursiveAsync() have not call FinalizeSkeletalMeshWithLODs , 

But, have some error at runtime . So , Is there anything wrong with the above steps?

Thanks a lot.

**Comment by rdeioris** [comment]
For triggering Mesh finalization you need to set the AsyncCallback. Without it the mesh will be basically useless.

**Comment by rtjia** [comment]
Thank you .  I will try it.
another question : about collision , I used these setting, but invalid :

	SkeletalMeshConfig.PhysicsAssetAutoBodyConfig.MinBoneSize = 0.005;//default = 20
	SkeletalMeshConfig.PhysicsAssetAutoBodyConfig.CollisionType = EglTFRuntimePhysicsAssetAutoBodyCollisionType::Box;
	SkeletalMeshConfig.PhysicsAssetAutoBodyConfig.CollisionScale = 100.1;
	SkeletalMeshConfig.PhysicsAssetAutoBodyConfig.bDisableOverlappingCollisions = false;
	SkeletalMeshConfig.PhysicsAssetAutoBodyConfig.CollisionTraceFlag = ECollisionTraceFlag::CTF_UseComplexAsSimple;

this is test model : 
[chair.zip](https://github.com/user-attachments/files/17251568/chair.zip)

Thanks again.

**Comment by rtjia** [comment]
Thank you.
yes , I do it,  but when i use runtimeSkelContext call FinalizeSkeletalMeshWithLODs() in AsyncCallback function for Mesh finalization , but crash, I trace code , it's seems like some infomation of runtimeSkelContext was lost .
