### ISSUE TITLE
Normals  inverse.

### ISSUE THREAD

**Issue by unsanedingding** [rdeioris/glTFRuntime-docs#27]
I use this setting ....
SkeletalMeshConfig.NormalsGenerationStrategy = EglTFRuntimeNormalsGenerationStrategy::Always;

Thanks a lot

**Comment by rdeioris** [comment]
Hi, i cannot reproduce the problem, normals looks definitely good:

![image](https://github.com/user-attachments/assets/a04e1874-629d-4636-b89b-166a0811fcb9)

Are you sure you are not changing the base matrix of the object in the loaderconfig ? This can potentially inverts the winding

**Comment by unsanedingding** [comment]
Thanks again.
