### ISSUE TITLE
Need to use enable per poly collision with skeletal mesh.

### ISSUE THREAD

**Issue by LeroRoh** [rdeioris/glTFRuntime-docs#5]
![image](https://user-images.githubusercontent.com/12895495/141877088-3e35e885-12a8-4861-bedf-13fa57ac791a.png)
When loading skeletal mesh, I hope check enable per poly option.

**Comment by rdeioris** [comment]
Added in https://github.com/rdeioris/glTFRuntime/commit/86f7a46e3851fc7eedd8076055ce48ae6fe49242
