### ISSUE TITLE
 Why the loaded model has more vertices than the original model

### ISSUE THREAD

**Issue by LittleWhited01** [rdeioris/glTFRuntime-docs#8]
Why the loaded model has more vertices than the original model

**Comment by rdeioris** [comment]
@LittleWhited01 you need to share the model, there are dozens of reasons

**Comment by LittleWhited01** [comment]
> @LittleWhited01 you need to share the model, there are dozens of reasons

How to avoid vertex increase？

**Comment by rdeioris** [comment]
please share the model otherwise it will be impossible to give you an answer
